version: 2

builds:
  - goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
      - '386'
    ldflags:
      - -X main.version={{ .Version }}
      - -X main.revision={{ .ShortCommit }}

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- if eq .Os "freebsd" }}FreeBSD
      {{- else }}{{ title .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}64bit
      {{- else if eq .Arch "386" }}32bit
      {{- else if eq .Arch "arm64" }}ARM64
      {{- else if eq .Arch "riscv64" }}RISCV
      {{- else }}{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ end }}

brews:
  - description: OPA Rego language server
    repository:
      owner: kitagry
      name: homebrew-tap
    directory: Formula
    homepage: https://github.com/kitagry/regols
    install: bin.install "regols"
