name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version-file: go.mod
      id: go

    - name: Get dependencies
      run: |
        go mod download

    - name: Vet
      run: |
        go vet ./...

    - name: Test
      run: |
        go test ./...
